---
- name: Verificar sitios IIS
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_port: 5985
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Obtener estado de los sitios IIS
      community.windows.win_iis_website:
        name: "Default Web Site"
        state: started
      register: iis_result
      check_mode: yes

    - name: Listar todos los sitios IIS y su estado
      ansible.windows.win_shell: |
        Import-Module WebAdministration
        Get-Website | Select-Object Name, State, PhysicalPath, @{n='Port';e={$_.bindings.collection.bindingInformation}} | ConvertTo-Json
      register: sitios

    - name: Mostrar sitios
      debug:
        msg: "{{ sitios.stdout | from_json }}"
